#!/bin/bash
export DISPLAY=:0
chmod o+rw /var/run/docker.sock
xhost +
cat > Dockerfile << EOF

FROM maven:3.6.0-jdk-11-slim AS build
COPY src src
COPY pom.xml .
RUN mvn -f pom.xml clean package install
ENV DISPLAY=:0
ENTRYPOINT ["mvn", "-q", "exec:java", "-Dexec.mainClass=com.sqlsamples.App"]

EOF

docker build -t appJava:latest . 
docker run --rm \
        --name appJAVA \
        -h Java_App \
        -e 'DISPLAY:"$DISPLAY"' \
        -v /tmp/.X11-unix:/tmp/.X11-unix app:latest

exit 0;
